batch_size: 64
train_steps: 500000
eval_every_n_steps: 10000
save_checkpoints_steps: 2000
keep_checkpoint_max: 10
input_pipeline_train:
    class: ParallelTextInputPipeline
input_pipeline_dev:
    class: ParallelTextInputPipeline
gpu_allow_growth: true
